language: es
pipeline:
- name: SpacyNLP
  model: "es_core_news_md"
  case_sensitive: False
- name: SpacyTokenizer
- name: SpacyFeaturizer
  pooling: mean
- name: DIETClassifier
  epochs: 200
  learning_rate: 0.001
  entity_recognition: False
  drop_rate: 0.25
  hidden_layers_sizes: 
    text: [256, 128]
    label: []
  transformer_size: 256
  number_of_transformer_layers: 2
  embedding_dimension: 30
  constrain_similarities: True
  
policies:
- name: RulePolicy
- name: MemoizationPolicy
  max_history: 4
#- name: TEDPolicy
#  max_history: 6
#  epochs: 200
