recipe: default.v1
language: es
pipeline:
- name: SpacyNLP
  model: es_core_news_md
  case_sensitive: false
- name: SpacyTokenizer
- name: LanguageModelFeaturizer
  model_name: bert
  model_weights: 'bert-base-multilingual-cased'
- name: DIETClassifier
  epochs: 150
  learning_rate: 0.001
  entity_recognition: False
  drop_rate: 0.25
  hidden_layers_sizes: 
    text: [512, 128]
    label: []
  transformer_size: 256
  number_of_transformer_layers: 4
  embedding_dimension: 30
  constrain_similarities: True
  #evaluate_on_number_of_examples: 0 #100
  #evaluate_every_number_of_epochs: 1
  #tensorboard_log_directory: ./tensorboard/DIETClassifier_heavy
  #tensorboard_log_level: epoch
#- name: FallbackClassifier
#  threshold: 0.65
#  ambiguity_threshold: 0.2
policies:
- name: RulePolicy
- name: MemoizationPolicy
  max_history: 4
