language: es
pipeline:
- name: SpacyNLP
  model: "es_core_news_md"
  case_sensitive: False
- name: SpacyTokenizer
- name: LanguageModelFeaturizer
  model_name: roberta
  model_weights: 'pretrained_models/roberta-base-bne'
- name: DIETClassifier
  epochs: 200
  constrain_similarities: True
  entity_recognition: False
- name: ResponseSelector
  hidden_layers_sizes: 
    text: [512, 128]
    label: []
  transformer_size: 256
  number_of_transformer_layers: 2
  embedding_dimension: 30
  epochs: 200
  retrieval_intent: faq
  constrain_similarities: True
- name: FallbackClassifier
  threshold: 0.5
  
policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 8
  epochs: 200
- name: RulePolicy
