recipe: default.v1
language: es
pipeline:
- name: transformers_intent_classifier.CustomNLUComponent
  model_name: dccuchile/bert-base-spanish-wwm-uncased
  batch_size: 12
  epochs: 20

policies:
- name: RulePolicy
- name: MemoizationPolicy
  max_history: 4
#- name: TEDPolicy
#  max_history: 6
#  epochs: 200
