language: es
pipeline:
- name: SpacyNLP
  model: es_core_news_md
  case_sensitive: false
- name: SpacyTokenizer
- name: SpacyFeaturizer
  pooling: mean
- name: DIETClassifier
  epochs: 150
  learning_rate: 0.001
  entity_recognition: False
  number_of_transformer_layers: 0
  embedding_dimension: 10
  drop_rate: 0.2
  hidden_layers_sizes:
    text: [256, 128]
  constrain_similarities: True
  #evaluate_on_number_of_examples: 0 #100
  #evaluate_every_number_of_epochs: 1
  #tensorboard_log_directory: ./tensorboard/DIETClassifier_ligth
  #tensorboard_log_level: epoch
#- name: FallbackClassifier
#  threshold: 0.65
#  ambiguity_threshold: 0.2
policies:
- name: RulePolicy
- name: MemoizationPolicy
  max_history: 4
#- name: TEDPolicy
#  max_history: 6
#  epochs: 200
