recipe: default.v1
language: es
pipeline:
- name: SpacyNLP
  model: "es_core_news_md"
  case_sensitive: False
- name: SpacyTokenizer
- name: rasa_nlu_examples.featurizers.dense.FastTextFeaturizer
  cache_dir: embedings
  file: 'cc.es.300.bin'
  #model_weights: 'pretrained_models/bert-base-spanish-wwm-cased'
  #model_weights: 'dccuchile/bert-base-spanish-wwm-cased'
#- name: HFTransformersNLP
  # Name of the language model to use
#  model_name: "bert"
  # Pre-Trained weights to be loaded
#  model_weights: "pretrained_models/bert-base-spanish-wwm-cased"
#  cache_dir: null
#- name: RegexFeaturizer
- name: DIETClassifier
  epochs: 200
  constrain_similarities: true
- name: ResponseSelector
  epochs: 200
  retrieval_intent: faq
#- name: FallbackClassifier
#  threshold: 0.5
  
policies:
- name: RulePolicy
- name: MemoizationPolicy
  max_history: 4
#- name: TEDPolicy
#  max_history: 6
#  epochs: 200
