language: es
pipeline:
- name: SpacyNLP
  model: es_core_news_md
  case_sensitive: false
- name: SpacyTokenizer
- name: LanguageModelFeaturizer
  model_name: bert
  model_weights: 'dccuchile/bert-base-spanish-wwm-cased'
- name: DIETClassifier
  epochs: 150
  learning_rate: 0.001
  entity_recognition: False
  number_of_transformer_layers: 0
  embedding_dimension: 30
  drop_rate: 0.2
  hidden_layers_sizes:
    text: [512, 512, 256]
  constrain_similarities: True
  #evaluate_on_number_of_examples: 0 #100
  #evaluate_every_number_of_epochs: 1
  #tensorboard_log_directory: ./tensorboard/DIETClassifier_ligth
  #tensorboard_log_level: epoch
#- name: FallbackClassifier
#  threshold: 0.65
#  ambiguity_threshold: 0.2
policies:
- name: RulePolicy
- name: MemoizationPolicy
  max_history: 4
#- name: TEDPolicy
#  max_history: 6
#  epochs: 200
