recipe: default.v1
language: es
pipeline:
- name: transformers_intent_classifier.CustomNLUComponent
  model_name: CenIA/distillbert-base-spanish-uncased
  batch_size: 16
  epochs: 10

policies:
- name: RulePolicy
- name: MemoizationPolicy
  max_history: 4
#- name: TEDPolicy
#  max_history: 6
#  epochs: 200
