language: es
pipeline:
#- name: SpacyNLP
#  model: "es_core_news_md"
#  case_sensitive: False
# - name: SpacyTokenizer
#- name: LanguageModelFeaturizer
#  model_name: bert
  #model_weights: 'pretrained_models/bert-base-spanish-wwm-cased'
#  model_weights: 'dccuchile/bert-base-spanish-wwm-cased'
  #model_weights: 'bert-base-multilingual-cased'
- name: HFTransformersNLP
  model_name: "bert"
  model_weights: "dccuchile/bert-base-spanish-wwm-cased"
- name: LanguageModelTokenizer
- name: LanguageModelFeaturizer
#  cache_dir: null
#- name: RegexFeaturizer
- name: DIETClassifier
  epochs: 200
  constrain_similarities: true
- name: ResponseSelector
  epochs: 60
  retrieval_intent: faq
  transformer_size: 256
  hidden_layers_sizes: {'text': [], 'label': []}
  number_of_transformer_layers: 2
  use_text_as_label: true
- name: FallbackClassifier
  threshold: 0.5
  
policies:
- name: RulePolicy
- name: MemoizationPolicy
  max_history: 4
#- name: TEDPolicy
#  max_history: 6
#  epochs: 200
