recipe: default.v1
language: es
pipeline:
- name: SpacyNLP
  model: es_core_news_md
  case_sensitive: false
- name: SpacyTokenizer
- name: SpacyFeaturizer
  pooling: mean
- name: DIETClassifier
  epochs: 100
  learning_rate: 0.001
  entity_recognition: False
  drop_rate: 0.25
  hidden_layers_sizes: 
    text: [256, 128]
    label: []
  transformer_size: 256
  number_of_transformer_layers: 2
  embedding_dimension: 30
  constrain_similarities: True
  random_seed: 42
  evaluate_on_number_of_examples: 150
  evaluate_every_number_of_epochs: 5
  tensorboard_log_level: epoch
  tensorboard_log_directory: ./tensorboard/DIETClassifier
#- name: FallbackClassifier
#  threshold: 0.7

policies:
- name: RulePolicy
- name: MemoizationPolicy
  max_history: 4
#- name: TEDPolicy
#  max_history: 6
#  epochs: 200
